### ISSUE TITLE
V2 Radar control menu gets corrupted 

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#104]
![screenshot from 2016-05-17 00-04-20](https://cloud.githubusercontent.com/assets/10214448/15310945/6e5412b4-1bc3-11e6-8cd1-b6fd60f79597.png)

Enter the timed transmit menu, then click on the radar window.
Happens with any menu item.

**Comment by canboat** [comment]
Ah, I know whereabouts that is going wrong, should be easy to fix.

**Comment by canboat** [comment]
Erik, please close if this is now indeed fixed.
