### ISSUE TITLE
Opening of the radar control if radar windows are hidden

### ISSUE THREAD

**Issue by canboat** [canboat/BR24radar_pi#110]
It can be hard to understand to get the radar control opened when only overlay is shown. The button should function more logically.

**Comment by NAHANNIV** [comment]
The "Radar Control..." button in the right click (context?) menu is not working.

**Comment by NAHANNIV** [comment]
Would it simplify things a bit if there were two radar buttons on the main toolbar ? One for Overlay and one for radar_window.

**Comment by canboat** [comment]
I think it works nicely now. Will remove context menu altogether, it is not needed anymore with the new behavior.
