### ISSUE TITLE
V2 Vertex array rendering not working with emulator

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#112]
Did not report this before, thought it was related to other know issue.

Works ok with the shader.

Also, with vertex array there seems to be some problem with transparency: there is a rotating wedge with a different transparency when using data from tcpreplay, but not consistent for the whole rotation.
This is a bit distracting, but a cool effect, like a CRT RADAR.

**Comment by canboat** [comment]
Hm, looks like these are indeed related. I get flashing alternate sectors in the emulator.

**Comment by canboat** [comment]
I can't even close O when the emulator is behaving rotten.
