### ISSUE TITLE
Radar Window reverts to default size when re-opened.

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#116]

**Comment by NAHANNIV** [comment]
In docked mode.

**Comment by canboat** [comment]
Either I don't have this issue, or it is already fixed after my commits to fix #115 and #118.

Can you recheck and if so tell me exactly what is wrong? I did the following steps:

- Start O,
- Dock 2 radar windows on right side and make them half the screen width,
- Quit O,
- Start O.

The radar windows were still docked in the same way and half the screen width. Then retried with a narrow window, same result.

**Comment by NAHANNIV** [comment]
Ubuntu x86 64 
Single RADARWindow
Docked
drag edge to half screen
Close RADAR with toolbar
Open RADAR with toolbar
Window is back to default docked size.

**Comment by canboat** [comment]
Duh, you're right. I was testing with quit/start of O, not stop/start of radar.

**Comment by canboat** [comment]
Should be fixed now. Thanks!
