### ISSUE TITLE
Head Up/North Up display and button text not always correct.

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#117]
Clicking the button always changes the radarwindow display but not always the button.

Seems to happen after clicking the button in overlay mode.

**Comment by canboat** [comment]
There is certainly a difference in how often these are computed and refreshed, but this shouldn't happen of course. It should also be impossible to choose when there is no heading data at all (neither from radar packets nor NMEA).

**Comment by canboat** [comment]
Not only is the button not always correct, the display can be incorrect as well when there is no NMEA data (but with heading in the radar packets.)

**Comment by canboat** [comment]
Fixed by commit [radarwindow 0a61db9]
