### ISSUE TITLE
Control window should not allow resize / maximize

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#119]
Double clicking the title bar on the control window expands the window but not the buttons; Same with dragging the borders of the window.
The window is also dockable. 

None of this is persistent, and perhaps it should just be disabled.

**Comment by canboat** [comment]
I can reproduce the resizing, you're right it would be better if this were disabled. I'll need to figure out how to tell wx this.

What do you mean with the window is dockable?

**Comment by NAHANNIV** [comment]
If I drag the control window to the border it docks and expands, covering the radarwindow, if it is also docked.

**Comment by NAHANNIV** [comment]
fixed
