### ISSUE TITLE
Control Dialog does not scale with scale set in OS

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#121]

**Comment by NAHANNIV** [comment]
Ubuntu x86 64 14.04

![image](https://cloud.githubusercontent.com/assets/10214448/15812098/c5ffacba-2b7e-11e6-922b-3251f2b11147.png)

**Comment by canboat** [comment]
Indeed it's funny looking. Weird that this is so different on GTK.

**Comment by NAHANNIV** [comment]
It works OK in the old version on the same system:

![image](https://cloud.githubusercontent.com/assets/10214448/15821937/d7f19388-2bc0-11e6-8613-80c25d2b33a0.png)

**Comment by canboat** [comment]
This is what I get on kubuntu 16.04 x86_64:

![screen shot 2016-06-06 at 23 15 03](https://cloud.githubusercontent.com/assets/1608058/15838194/04b01cf6-2c3d-11e6-8df0-be2d1afa628d.png)

Kinda weird that it should work on one system but not another.

**Comment by canboat** [comment]
Can you try it now? I fiddled a little with the disable options and the way the zone type options are drawn. Do the controls for range and bearing go disabled/enabled now depending on the zone type?

**Comment by NAHANNIV** [comment]
Still looks the same.

There is only a box for inner range, I can use the TAB key to select Outer, start, and end.
When selected the line below the item turns red.
I can enter data but can't see it.
When circle is selected Start and end are inactive.

**Comment by canboat** [comment]
Is the dialog the same height as when you’re not in a Guard Zone?

Can you show a screen dump with radar A in the ‘home’ view of the dialog (with transmit/standby at the top) and radar B with the Guard Zone pane active?

**Comment by NAHANNIV** [comment]
The Control window is always the same height.

For some reason I can no longer get the emulator to work with RADAR B.
So here is the opposite of what you asked for:

![image](https://cloud.githubusercontent.com/assets/10214448/15856214/3dc5eb8e-2c82-11e6-8a0b-ae2d16d01ff0.png)

**Comment by canboat** [comment]
I see what is going on here, the Guard zone dialog is compressed because the radar dialogs are as well. You can see how all buttons are missing the top and bottom pixels.

What resolution is this? 1024x600?

**Comment by NAHANNIV** [comment]
1920 * 1080

**Comment by canboat** [comment]
Ah, I see the problem now. If I use Ubuntu + Unity and go to Settings > Display and set "Scale for menu and title bars" to 1.5 or higher I get the same issue. I need to scale the height of the button bars with the height of the text, at least on GTK and maybe OS X and Windows.

**Comment by NAHANNIV** [comment]
Working with Scale set to 1:

![image](https://cloud.githubusercontent.com/assets/10214448/15860339/a37bffae-2c96-11e6-96de-abf5454d8d10.png)

**Comment by canboat** [comment]
Much nicer :-) but even then the buttons are not high enough in Unity. GGGGGGGrrrrr!

Will have to figure out something dependent on OS I guess. And/or maybe even an override in the ini file so that we get a workaround if I get it wrong…

**Comment by NAHANNIV** [comment]
All except timed transmit is visible now.

However, the control window seems very big and some buttons seem to have more whitespace top and bottom than others ? For instance, Transmit, Hide Radars, Overlay On Head Up have very little wasted white space, while most of the others do.

![image](https://cloud.githubusercontent.com/assets/10214448/15880982/5125e692-2d00-11e6-9108-18cb11676b32.png)

**Comment by canboat** [comment]
Still not right on GTK, MSW and MAC work OK.

**Comment by NAHANNIV** [comment]
Seems OK on Ubuntu 14.04.
