### ISSUE TITLE
Info Window displayed while editing preferences.

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#123]
If the RADAR is transmitting with overlay on while the preferences menu is displayed, the Info window pops up (incorrectly)showing no position data:
 
![image](https://cloud.githubusercontent.com/assets/10214448/15812299/5931ff22-2b81-11e6-8f52-9b0f6383d13e.png)

**Comment by canboat** [comment]
I will have to think about this. It's not our preferences dialog but the OpenCPN Options dialog that causes this. They don't refresh the main chart window nor anything else when this is open, so we don't get any calls from OpenCPN at all, and thus the plugin complains that there is no boat position, heading or variation.

**Comment by canboat** [comment]
Fixed this as much as reasonably possible, see comment on commit 183a9f8.

**Comment by canboat** [comment]
I found a different nasty solution that should make this really nicely behaved. 

When opening the message box I check that there is no modal dialog visible. The only modal dialog in O happens to be the Options dialog, so this works well. Even if there are other modal dialogs then the logic is still the same as you don't want pop-ups when a modal dialog is shown.
