### ISSUE TITLE
RADAR tries to draw when OpenGL is off

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#124]
With OpenCPN OpenGL off.
If the info window is closed, then the RADAR plugin started with the toolbar Icon a blank White screen is displayed.

**Comment by canboat** [comment]
I couldn't reproduce after adding this small change.

**Comment by NAHANNIV** [comment]
What I see now (Ubuntu 14.04 X86_64) is the RADAR window flashes on briefly then turns off.

I think if OpenGL is not enabled and someone tries to turn the RADAR on re-displaying the info window (showing the missing OpenGL requirement) would be more helpful.
