### ISSUE TITLE
No Emulator for 4G RADAR B

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#126]
Was working, not any more.

**Comment by NAHANNIV** [comment]
Working again after re-starting OpenCPN ? Not sure how to re-create ?

**Comment by canboat** [comment]
Never seen this either. Close for now? We can always re-open.

**Comment by NAHANNIV** [comment]
This happens on a new install, or if the opencpn.conf is deleted.

Delete opencpn.conf
start opencpn
configure opengl
configure radar plugin with emulator and dual radar on
start radar

Radar B shows NO RADAR.

Restart OpenCPN

Radar B shows emulator.

Minor issue, but might show up in other ways.
