### ISSUE TITLE
Guard Zone Outline Not shown on Overlay

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#127]
Perhaps this is by design ?
Could it be an option in preferences ?

**Comment by canboat** [comment]
Yes, this is by design as it is so cluttered. Also the plotters don’t do this.

**Comment by NAHANNIV** [comment]
Option check Box to "Show Guard Zone in Overlay" in preferences would be a wish list item.

**Comment by canboat** [comment]
Should probably do this for overlay-only aficionados.
