### ISSUE TITLE
Guard Zone Not working with Emulator

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#128]
![image](https://cloud.githubusercontent.com/assets/10214448/15881288/c03de67c-2d02-11e6-989e-eadde5263fb7.png)

**Comment by NAHANNIV** [comment]
Bogeys are counted and alarm goes off even when the emulator data is not overlapping the guard zone.

**Comment by canboat** [comment]
Actually the bogeys are counted correctly but the emulated data is drawn at the wrong zoom level.
