### ISSUE TITLE
4G Dual RADAR with Overlay=RADAR_A Window=RADAR_B

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#130]
For 4G Dual RADAR, I wish there were a way to have one RADAR as the overlay and the other one in the window, and be able to toggle this configuration on and off from the toolbar. Now it always comes back with two windows even after I close one.

**Comment by canboat** [comment]
Irritates me as well 👍

**Comment by canboat** [comment]
Can you check whether you like the current behavior?

**Comment by NAHANNIV** [comment]
Looks good,

Thanks,
