### ISSUE TITLE
Need a way to raise timed out control window in overlay only mode

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#131]
The only way to get the control window back if it times out in overlay only mode is to toggle the RADAR on/off with the toolbar icon.

I think it would be better to re-instate the context menu item "Show RADAR Control".

**Comment by canboat** [comment]
Added both show/hide and show control. This way the use of the toolbar is completely optional.

**Comment by NAHANNIV** [comment]
Perfect !
