### ISSUE TITLE
Feature request: scroll wheel or pinch to change range in radar window

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#138]
Using menu for range is annoying with range setting requiring many mouse clicks from the top level menu.

**Comment by canboat** [comment]
Super idea!

**Comment by canboat** [comment]
Let me know whether this works good enough. I'm seeing a lot of mousewheel events so to prevent too fast zooming I implemented a crude limit of 1 zoom level per second. This is maybe too slow.

**Comment by marcus-aa** [comment]
Very good idea, Please make the direction (in/out) configurable.

Wen using a professional navigation joystick that uses a twisting motion for mouse scroll, OCPN zooms the wrong direction....

Often the sensitivity also needs to be configurable to work well with different devices, and it's nice to get faster zoom when you turn further, but a step limiter is also good, try 2-3 steps/sec.

I'll be back at the boat for more testing next week!

**Comment by canboat** [comment]
Marcus, good suggestions. Will do.

**Comment by canboat** [comment]
Unfortunately "pinch" is only supported in wxWidgets 3.1.0, and OpenCPN runs with 3.0.2 so this will have to wait a little. Double finger scroll becomes zoom on a Mac trackpad, which is fine.

**Comment by canboat** [comment]
I'm thinking I could also add "-" and "+" buttons on screen, like the plotters.

**Comment by marcus-aa** [comment]
On 2016-06-20, at 21:34, Kees Verruijt wrote:

> I'm thinking I could also add "-" and "+" buttons on screen, like the plotters.

That would be great when running on traditional single-touch monitors.

/M

**Comment by canboat** [comment]
Works great now (I could not test with actual radar when committing 8 days ago.)
