### ISSUE TITLE
Bearings in the radar window are not correct

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#140]
The bearings on the outer range ring are not correct.

In north up, HDM is at the top.

In head up north is at he bottom.

**Comment by NAHANNIV** [comment]
Perhaps this is related to ebl vrm cursor placement?

**Comment by canboat** [comment]
Or the other way around! I guess I only tested the boat at the dock, which happens to lie almost exactly due south :-)

**Comment by canboat** [comment]
Now running VDR with slow rotation, and you're absolutely right...
