### ISSUE TITLE
Guard zones (1,2) are not alarming

### ISSUE THREAD

**Issue by Hakansv** [canboat/BR24radar_pi#149]
Radar type: BR24(3G), OS: Win10, OCPN: 4.4.0, RW: 2.614. All built by VS2013. 
Guard zones (1,2) are not alarming, neither sector nor circle.
See attached picture where an alarm should have been received.

![guard_zone](https://cloud.githubusercontent.com/assets/7202854/16244720/b5b9d962-37fd-11e6-8a5d-ae9a214ba15d.PNG)

**Comment by canboat** [comment]
Weird. I must admit I've been testing this mostly with the separate PPI radarwindow. I'll check that it works with radar overlay only.

**Comment by canboat** [comment]
If only all bugs were this easy! Can you close if it works for you as well?

**Comment by canboat** [comment]
Sorry, it is still not correct. Values are calculated now but not the correct ones.
