### ISSUE TITLE
Radar control menu location is not saved

### ISSUE THREAD

**Issue by canboat** [canboat/BR24radar_pi#158]
According to Håkan in issue #157 

BTW: Kees, pls recover saving radar menus last position. That function was recently lost.

**Comment by canboat** [comment]
The designed behavior is that if you move a PPI radar window that the next time that the radar window comes up directly over where you press the new "Menu" button on the PPI display. Previously you could click anywhere in the PPI display, but this is not usually reserved for setting the cursor.

When you're not moving a PPI window or don't have them displayed the design is that the control menu comes up in the previous location. You're right, it doesn't.

**Comment by canboat** [comment]
Can you please test? I like the current behavior. You should not notice anything with the radar windows closed. If you do have one or more open, and you move the panel and close the control then the next time it opens on the top right of the panel (directly over the menu button.)

**Comment by Hakansv** [comment]
Position is now saved, thanks.
re: "next time it opens on the top right of the panel (directly over the menu button."
Yes correct positioned but, in Win10, behind the radar window thus invisible. I've to move radar window to see it.

**Comment by canboat** [comment]
Getting over/under right in all OS is a crime against humanity in wxWidgets. They’re supposed to solve this for you, but ...
