### ISSUE TITLE
Need to read the manual to find out how to turn on trails.

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#161]
Nobody likes to have to read the manual!

Could the colour be forced if trails is selected?

Of course this idiot knows how to do it now, but There may be others.

**Comment by canboat** [comment]
You're welcome to start changing the manual on opencpn.org ;-)

I changed the default to multi-color, but flipping this by choosing something else is a bad idea because someone may want unicolor as it uses fewer resources (GPU + CPU).

**Comment by NAHANNIV** [comment]
Ok, no problem, just thought I'd mention it.
Take a break , you deserve it!

I Can't close for some reason?
