### ISSUE TITLE
v2.628 Radar Control is out of screen

### ISSUE THREAD

**Issue by Hakansv** [canboat/BR24radar_pi#162]
The new ->Read to infi file is positioning the control to -1000, -1000 and is thus invisible:
ini file:
Radar0ControlPosX=-10000
Radar0ControlPosY=-10000
code:
pConf->Read(wxString::Format(wxT("Radar%dControlPosX"), r), &x, OFFSCREEN_CONTROL_X);
pConf->Read(wxString::Format(wxT("Radar%dControlPosY"), r), &y, OFFSCREEN_CONTROL_Y);

**Comment by canboat** [comment]
See #158
