### ISSUE TITLE
Radar Controls is stealing focus

### ISSUE THREAD

**Issue by Hakansv** [canboat/BR24radar_pi#167]
Windows 10
Radar control seems to aggressive in getting focus. When control is open it takes focus every second or so. That makes it impossible to use keyboard shortcuts in OCPN. If I click on O canvas to get focus for shortcuts, like +/- zoom, Radar Controls takes it back in a second. The main purpose would be to give focus to OCPN as much as possible. When sailing I expect a keyboard action to affect O at once.

**Comment by canboat** [comment]
Ah this is a result from my adding an extra 'raise' two days ago because you complained it was hidden. Can you try with this line removed, I can't access the source today but you ought to be able to find it pretty easily.

**Comment by Hakansv** [comment]
Correct. Removing Raise() in UpdateDialogShown() solves this issue.
You'll will have to find another method to not hide the control behind radar window when the window's icon is used. 

And when focus is in OCPN it takes two clicks to use a radar control menu. One to activate the control and one to open the menu point.
You don't have a windows system to test in, do you?

**Comment by canboat** [comment]
The solution I came up with is neither simple nor pretty, but it is as close as I can get without major work. Basically a floating radar A window can overlap the control for radar B and vice versa, but the control of the raised radar window will always be visible.

**Comment by canboat** [comment]
oh, and of course docked radar windows never hide any controls anymore.

**Comment by Hakansv** [comment]
I'll do live test tomorrow. Radar control is much better and, yes, radar window is not covering it. But the guard alert is a bit nervous. See attached video. --- No not supported. I'll send a mail.

**Comment by Hakansv** [comment]
The control is now visible all time, good.
You still need two clicks to activate a menu point when OCPN has focus.
Guard alert blinking waits for solution. (It seems to alter between radar control, short blink, and alert box.)

**Comment by Hakansv** [comment]
Commit: Revert to old way of creating control dialog on MSW
- When OCPN has focus I still have to click two times on a radar control button to activate. On first click radar control gets focus, next click activates the button. Using a control in for example grib_pi it's enough with one click for the same scenario.
- Guard alert is still the same; switching between alert and radar control and is steeling focus from OCPN

**Comment by canboat** [comment]
@Hakansv I tested today with Windows 10, and I also need to click twice. Let me see whether this is something that can be fixed in the plugin.

**Comment by canboat** [comment]
Email from @Hakansv and @douwefokkema confirms reparenting solves this.
