### ISSUE TITLE
New SVG icon all black in Windows

### ISSUE THREAD

**Issue by Hakansv** [canboat/BR24radar_pi#170]
Git pull today 07-13 ~15:00 In Win 10
The new icon is at OCPN start some rings with a question mark, then after 1 second it's all black. During transmission a shadow of something can be perceived.
This icon outlook is the same in both traditional and Journeyman tools styles. (See attached pic,)
![rw-svg icon journeyman](https://cloud.githubusercontent.com/assets/7202854/16807268/13c6f104-4918-11e6-8182-57e7cb38fb66.PNG)
![rw-svg icon traditional](https://cloud.githubusercontent.com/assets/7202854/16807269/13ccb5d0-4918-11e6-97d2-ad816f27707a.PNG)

**Comment by canboat** [comment]
See #143 -- it's not all black, it's got four green radar range icons. Unfortunately at your resolution you can't really make out the rings properly. 

I will update #143 to increase the width of the green rings a little so they can be seen better at low res.
