### ISSUE TITLE
Old scan drawn momentarily when radar is turned on.

### ISSUE THREAD

**Issue by NAHANNIV** [canboat/BR24radar_pi#175]
Today I ran the RADAR at the dock before setting out, then turned it off, leaving OpenCPN running.
Once out on the water in a much clearer area I turned the RADAR back on.
Part of the RADAR picture at my dock was displayed momentarily before being replaced by the correct display.

I can also see this if I switch between emulator and live RADAR.

**Comment by canboat** [comment]
@NAHANNIV please close if it works for you. I will be able to report back in a couple of days after sailing and gaining access to WiFi again.

**Comment by NAHANNIV** [comment]
Not moving for a few days, so I tested this by switching on the emulator, closing radar, turing off emulator, opening radar.

The emulator image still comes up momentarily.

**Comment by canboat** [comment]
The way this was fixed does not fix it for the emulator.

Met vriendelijke groeten,
Kees
