### ISSUE TITLE
On start of OCPN guard alarm rings once

### ISSUE THREAD

**Issue by douwefokkema** [canboat/BR24radar_pi#183]
No guard zones are set

**Comment by canboat** [comment]
I cannot reproduce this. Does this still happen for you with todays build (2.804)? I fixed some initialization errors that may have caused this for you.

**Comment by douwefokkema** [comment]
Yes, same as before with 5cd4b8a

**Comment by canboat** [comment]
BTW -- have you tried building a complete package (for windows: `cmake --build . --config release --target package`) as the default sound is now a voice text, instead of just "ding".

**Comment by douwefokkema** [comment]
Can no longer be reproduced. Suspect cause outside radar.
