### ISSUE TITLE
OCPN crashes when disabling radar_pi plugin

### ISSUE THREAD

**Issue by douwefokkema** [canboat/BR24radar_pi#187]
Radar on Standby, start O. Tools, plugins, select br24radar_pi. Click "disable". OCPN crashes.

**Comment by canboat** [comment]
Hm this is probably the same bug as the DeInit on close of O. But hopefully this reproduces for me. 

Are you able to attach a debugger before this action and get a stack trace??

**Comment by canboat** [comment]
Nope, this works for me as well.

Are you using the RelWithDbgInfo version or Release? The Debug version is NOT compatible with production OpenCPN releases on Windows.

**Comment by canboat** [comment]
Maybe test with a full installation package -- `cmake --build . --config release --target package` ?

**Comment by canboat** [comment]
I'm running out of ideas now, by the way. I can't get ANY version to crash anymore, Linux / Mac / MS. Also even `helgrind` on Linux doesn't complain much (except for some innocent variable clashes).

**Comment by canboat** [comment]
@douwefokkema confirms fixed.
