### ISSUE TITLE
Radar_pi using COG as heading even when moored

### ISSUE THREAD

**Issue by douwefokkema** [canboat/BR24radar_pi#188]
In rel 1.3x there was a preference to enable / disable the use of COG as heading. When this option is not there, it is better to disable the use of COG as heading completely for overlaying the radar on the chart. Also Lowrance plotters will not do an overlay based on COG.
This issue is of course only shown when the HDM or HDT drops away. In that case the info display should show, instead of switching over to COG.

**Comment by canboat** [comment]
Fixed this in commit c8a1de5ac701b736edbfdbde371ff8ce0cbdce58 but referenced the wrong issue in the commit message.
