### ISSUE TITLE
BR24/3G Radar picture is rotated incorrectly

### ISSUE THREAD

**Issue by Hakansv** [canboat/BR24radar_pi#196]
Win10 - VS2013
OCPN:  4.5 source fetched today 16-08-09
BR24radar_pi: branch radarwindow source fetched today 16-08-09. (Last commit: "Add extra help files for.....")
>>
Radar echos are 180 degr misplaced. (Guard zones are correct and consequently 180 degr misplaced when radar head is adjusted.)
<<
BR24 ver 1.32 and previous "radarwindow" are correct 
![br24_v_2 0](https://cloud.githubusercontent.com/assets/7202854/17516041/604909ca-5e3c-11e6-9700-cc2e0d977523.PNG)

**Comment by canboat** [comment]
What do you see on the PPI radar window in heads up and north up mode?

**Comment by Hakansv** [comment]
Oooh - sorry not on board but home again. I can go back and and check if important!
I think, absolutely not sure, it was 180 degr false in heads up.

**Comment by canboat** [comment]
> Oooh - sorry not on board but home again. I can go back and and check if important!
> I think, absolutely not sure, it was 180 degr false in heads up.
> 
I think it may be because we’re no longer ignoring Heading coming from the radar on BR24 and 3G models. This was added in issue #186. Before we only used this heading field in the data when it came from a 4G. And you might not have a RI-10/11 hooked up to your BR24, and if so, not a compass hooked up?

Please see what happens if you go to Preferences and set the (also new) “Ignore heading from radar”.

If this fixes it, please upload a `pcap` file made with the radar transmitting (an old one is fine, I know you have those).

**Comment by Hakansv** [comment]
I don't use the RI-10/11 it's a direct IP connection to my PC, correct. The heading is coming via OCPN and NMEA from a stand alone compass.

OK - I'll test the “Ignore heading from radar”  and also check the PPI window hopefully later this afternoon.

All my pcap's are still here:  https://dl.dropboxusercontent.com/u/5209364/captures.zip

**Comment by canboat** [comment]
I just checked with official released v2.0 code built by the Ubuntu packagers (can’t get more official than that) and it works fine with my 4G, so I am now almost 100% sure its this new “feature” (which may turn out to be broken).

> I think it may be because we’re no longer ignoring Heading coming from the radar on BR24 and 3G models. This was added in issue #186. Before we only used this heading field in the data when it came from a 4G. And you might not have a RI-10/11 hooked up to your BR24, and if so, not a compass hooked up?
> 
> Please see what happens if you go to Preferences and set the (also new) “Ignore heading from radar”.
>

**Comment by marcus-aa** [comment]
It's probably possible that if the radar sees no valid heading from RI10/11 it sends 0° (or some other undefined value and sets a (yet unknown to us) bit to indicate "no valid heading", but we interpret that as a valid heading ?

**Comment by canboat** [comment]
> On 10 Aug 2016, at 15:39, Marcus AAkesson <notifications@github.com> wrote:
> 
> It's probably possible that if the radar sees no valid heading from RI10/11 it sends 0° (or some other undefined value and sets a (yet unknown to us) bit to indicate "no valid heading", but we interpret that as a valid heading
> 
> 
Yes, and it probably sends a different value for “no valid heading” than a 4G. The 4G sends 0xffff. BTW Marcus, is it correct in your 3G dump that the ships heading was South East?

**Comment by canboat** [comment]
I just noticed that Matt Paulin has difficulties with this with his 3G as well, and in particular this image is interesting:

![heading issue](http://www.cruisersforum.com/forums/attachment.php?attachmentid=129280&d=1470799815)

it shows that head up mode is out by about 20 degrees, and his variation happens to be 19.5 degrees. Another reason to fix #194!

**Comment by canboat** [comment]
I just realised that the two persons who reported issues with this use no RI-10/11. This seems to confirm that the RI-10/11 repackages the packets with the heading data.

**Comment by marcus-aa** [comment]
>I just realised that the two persons who reported issues with this use no RI-10/11. This >seems to confirm that the RI-10/11 repackages the packets with the heading data.

Can't follow you here, the RI doesn't participate in IP traffic at all. Or what do you mean with repackages?
The problems reported are consistent with having no heading _connected_ to the radar. Without RI you don't get heading into radar, but there should be no difference if RI is used but not connected to heading source, or if no RI is used... ?

**Comment by canboat** [comment]
> Can't follow you here, the RI doesn't participate in IP traffic at all. Or what do you mean with repackages?
We have no way of knowing how the RI-10 works. I do know it has a bigger SOC than you'd expect. I was expecting something like in a IS40 or ST10, that takes the N2K data and send it in some simple serial format to the radome on one of the free RJ45 wires, but in my memory there is a huge chip in there which suggests it does a bit more. One way for this to make sense is that it actually acts as a router, and takes the IP data coming from the radar and adds the heading to the packets. The other way is that it sends the N2K heading and sends it as Ethernet packets to the radar which then adds that data directly. But this is all just conjecture...

> The problems reported are consistent with having no heading connected to the radar. Without RI you don't get heading into radar, but there should be no difference if RI is used but not connected to heading source, or if no RI is used... ?
Correct.

**Comment by Hakansv** [comment]
Now tested on my BR24 radar scanner. Works great also with heading from OCPN. Radar picture position is at the correct angle as well as the guard zones. Both chart overlay and radar window are correct. All concerned properties settings was at default stage.
The issue is solved for me as well.

**Comment by MattPaulin** [comment]
Ok, if it's fixed, were can I download a Windows version with the patch? I really must learn how to compile stuff sometime! Thx everyone.

**Comment by Hakansv** [comment]
Matt.
Here's mine: https://dl.dropboxusercontent.com/u/5209364/br24radar_pi-2.0-win32.exe
From today's source including commit : "Show firmware date"
Pls also report if radar menu on your system is viewed correct. (Compare issue #197 )

**Comment by MattPaulin** [comment]
Thanks Hakan, 
![radar pic](https://cloud.githubusercontent.com/assets/9459341/17638183/80a6b8c2-613c-11e6-8fd2-8dc06f7868f4.jpg)
Radar menu in that version is not useable on my PC...

**Comment by Hakansv** [comment]
Kees has changed so now it's fine on my Win10. My link is updated.
https://dl.dropboxusercontent.com/u/5209364/br24radar_pi-2.0-win32.exe
Pls try this though it's compiled using OCPN resent master O version 4.5.0. Hopefully no difference for you and BR24radar_pi. If not please revert and I've a O 4.5.0 install exe

**Comment by MattPaulin** [comment]
Thanks Hakan, I'll install on the boat in the morning and report back - off out to dinner right now.

Cheers

Matt Paulin
+64221539176
www.neptunes-gear.com

**Comment by MattPaulin** [comment]
Tested that one, same issue, menu unreadable.

**Comment by Hakansv** [comment]
Matt. Thanks for your time to test this.
To be sure and to sort out far outs I've tested the new BR24.._pi on O 4.4.0 and that's not the cause, worked fine for me.
I can't say I've any particular next step to test. 
Kees - any ideas? 
....Old remains in the config file??
....How come the big difference between Matt's plugin windows, BR24/Tactics? BR24 has round corners the others sharp? It's not like that on my system, see my screenshot.

![skarmklipp](https://cloud.githubusercontent.com/assets/7202854/17641971/3d6e38e8-6135-11e6-8d51-c6bd509644fa.PNG)

**Comment by Hakansv** [comment]
Matt. How's the radar info box?

**Comment by canboat** [comment]
> ....Old remains in the config file??
> ....How come the big difference between Matt's plugin windows, BR24/Tactics? BR24 has round corners the others sharp? It's not like that on my system, see my screenshot.
> 
> 
The tactics data is (I guess) not a separate wxDialog but an AUI box, and it is certainly not using wxButton, there are millions of different ways to style windows dialogs anyhow.

**Comment by Hakansv** [comment]
Misunderstanding...
What I meant to emphasize was: Why are the boxes so different on Matt's system but equal on mine?

**Comment by Hakansv** [comment]
@MattPaulin Please try again. We've made a small change for a test: https://dl.dropboxusercontent.com/u/5209364/br24radar_pi-2.0-win32.exe

**Comment by MattPaulin** [comment]
Great, all working fine with this one!! Thanks guys :-)
