### ISSUE TITLE
Characters drawn on PPI window outside the ASCII characterset are drawn distorted

### ISSUE THREAD

**Issue by bc38** [canboat/BR24radar_pi#207]
The problem with inscriptions display in the window of the radar in Cyrillic (Russian) confirmed. Menu button also does not correctly displayed. Screenshot attached. Labels and Menu in ENG displayed normally. I made a full translation plugin on crowdin.
http://www.cruisersforum.com/forums/attachment.php?attachmentid=129436&d=1471022937

**Comment by canboat** [comment]
@Hakansv will create a new set of PO files soon from Crowdin.

**Comment by canboat** [comment]
It's a bug in TexInfo.cpp, which I borrowed from OpenCPN.

**Comment by Hakansv** [comment]
Crowdin has been updated with new strings to translate more or less every second day. Development is still ongoing so I haven't pushed translations files to Canboat source for a while. I'll do that when source is stable and most translators are ready.
Of course - I you wish to test I can push what we have so far, please advice.

**Comment by canboat** [comment]
I think we can wait, the word “Menu” now seems to be correct.
