### ISSUE TITLE
10 minute trails are displayed same way as continuous trails

### ISSUE THREAD

**Issue by canboat** [canboat/BR24radar_pi#211]
Reported by @douwefokkema by email.

**Comment by canboat** [comment]
I cannot reproduce (using emulator, but that should have zero effect):

<img width="475" alt="screen shot 2016-08-18 at 23 35 57" src="https://cloud.githubusercontent.com/assets/1608058/17791664/a950ea86-659c-11e6-981d-b2914d813475.png">

<img width="480" alt="screen shot 2016-08-18 at 23 36 09" src="https://cloud.githubusercontent.com/assets/1608058/17791669/b1f4c8f6-659c-11e6-99f0-567d07772016.png">

Looks exactly as designed (considering my trails go from light blue (recent) to dark blue (old)).

**Comment by douwefokkema** [comment]
Tested in harbor with more distinct colors:
10 minute trails switch after about 3 min to second color. After that they seem to last forever (now running 1 hour). Except when they disappear, which happens incidentally, though this could have a different cause (dropping heading or position?).

**Comment by douwefokkema** [comment]
Solved in 6068d911f. Can be closed.
