### ISSUE TITLE
Trails get interrupted when switching off / on

### ISSUE THREAD

**Issue by douwefokkema** [canboat/BR24radar_pi#222]
When trails are switched off and later on again, the "old" part of the trail will be shown again if still on the screen. Though not really wrong, it is not nice. Two solutions can be thought off:
- clear trails when switching trails off
or
- continue recording trails all the time and immediately display the full trail when switching trails on.
The second seems to be the preferred one. Disadvantage is the higher CPU load caused by the continues recording of true trails. See next issue.

**Comment by marcus-aa** [comment]
Second option is clearly the best. For safety it is preferred if both relativt/true switching as well as on/off/time change can be done without loss of trails.

For example, when navigating, you are unsure of the passing conditions and want to switch on trails, but if they are not then available immediately it can be confusing before they are built up.

(Switching between true and relative is probably solved, but even more important that we don't lose all trail data when switching there)

Is there a way to switch trail display on and off without changing time to 0 ? I would prefer that, on/off should be an easier accessible setting than the length.

/ Marcus
