### ISSUE TITLE
RM indicator hidden unless trails=on

### ISSUE THREAD

**Issue by marcus-aa** [canboat/BR24radar_pi#226]
The RM indicator for Relative Motion is only displayed if trails are either R or T.

RM(R) and RM(T) is correctly displayed, but never just RM.

**Comment by canboat** [comment]
Correct, it is always RM so no real point (yet) but might as well remind you on-screen.

**Comment by marcus-aa** [comment]
Minor issue, but since we are hoping for a TM mode later it would be logical to display RM all the time now.
