### ISSUE TITLE
No way to set true cursor bearings when in head up mode ?

### ISSUE THREAD

**Issue by marcus-aa** [canboat/BR24radar_pi#228]
If heading is available, and correctly displayed on the outer heading circle in the radar window, I would prefer if cursor bearings are also true.

Only use relative bearings if no heading available? Or do we need another button....

Or have I just not found it... ?

**Comment by canboat** [comment]
Yes, at the moment we show relative beharing in head up mode. This is what the Navico plotter does. Show both? Preferences page is another possibility. 

Met vriendelijke groeten,
Kees

**Comment by canboat** [comment]
The new course up mode developed by Douwe will give you true bearings. Head up mode is meant for users without a compass now.

**Comment by canboat** [comment]
@marcus-aa is the course up mode good enough? If so please close, otherwise comment what your reasoning is.

**Comment by canboat** [comment]
Heading up mode is now replaced by Heading up (Stabilized) when you have a compass heading, and this shows bearings in true degrees.
