### ISSUE TITLE
AIS/ARPA texts show up as black instead of selected color when OpenCPN is not using English

### ISSUE THREAD

**Issue by canboat** [canboat/BR24radar_pi#253]
The "ARPA text color" doesn't work for some reason.

**Comment by Hakansv** [comment]
Confirmed for Win10 and XP. The ARPA and AIS target names are there but colored black only and though not visible on the black background.

**Comment by canboat** [comment]
It's different -- it has to do with the language used in OpenCPN. For some reason the font names we have to use are the translated ones, but they don't work.

**Comment by canboat** [comment]
This is fixed by commit https://github.com/canboat/BR24radar_pi/commit/6b79ca38e292049060fe89a4b0b68e056b0d55dc which I accidentally checked in with too many files.

**Comment by canboat** [comment]
Please reopen if someone still has this issue.
