### ISSUE TITLE
OCPN right click canvas menu is corrupt.

### ISSUE THREAD

**Issue by Hakansv** [canboat/BR24radar_pi#255]
Some BR24 parts of this menu has been destroyed and one function is doubled.
Set MARPA target is double.
"Radar Control..." and the translated "Radar Inställningar" would be the same?
Delete (M)ARPA target is missing
Delete all (M)ARPA targets is missing.
See picture below:

![rightclich menu](https://user-images.githubusercontent.com/7202854/29038976-cfb40b8a-7ba9-11e7-82a6-7cb054aa9b6a.PNG)

**Comment by canboat** [comment]
I can get the double menu only if I switch languages (but then I also get crashes) or if I have 2 installations of the dll installed.

The "Delete (M)ARPA" records were only shown once you had any (M)ARPA targets, but then they would stay there even if the count dropped to zero. I have now fixed this -- the menu items are there always, but when the target count is zero the delete items are greyed out and cannot be clicked.

**Comment by Hakansv** [comment]
Fix confirmed. 
Thanks
