### ISSUE TITLE
Internationalism for ver 3.0

### ISSUE THREAD

**Issue by Hakansv** [canboat/BR24radar_pi#270]
Pot file for v 3.0 is now loaded to Crowdin and is ready for translations.
New po-files to be cached before final release.

**Comment by Hakansv** [comment]
Kees; are we ready for new po-files or should we wait for possible more translations. Or -  You I await your request a day or so before you're ready?  (I'm not sure of recent release schedule.)

This is Crowdin status as of today:
![bild](https://user-images.githubusercontent.com/7202854/30511755-dbe74fca-9adf-11e7-8fac-181f9eccfc46.png)

**Comment by canboat** [comment]
Hi Håkan,

I think we should be ready, so if you can produce a pull request please? 

Kees

**Comment by Hakansv** [comment]
PR's done.
