### ISSUE TITLE
Revise texts on MARPA buttons

### ISSUE THREAD

**Issue by canboat** [canboat/BR24radar_pi#275]
Instead of 'Set (M)ARPA Target' use 'Acquire Target'.
Instead of 'Delete (M)ARPA Target' use 'Delete Target'.
Instead of 'Delete all (M)ARPA Targets' use 'Delete all Targets'.

Add 'Delete all targets' button to PPI menus.

**Comment by canboat** [comment]
Once this is done we'll need to upload into crowdin again.

**Comment by Hakansv** [comment]
A "Target" can be misunderstood as an AIS target as well so we may mention (M)ARPA somewhere I think.
