### ISSUE TITLE
Radar B overlay never redraws more than once a second

### ISSUE THREAD

**Issue by canboat** [canboat/BR24radar_pi#289]
The timer is only on Radar A, and only looks at its own overlay.

**Comment by NAHANNIV** [comment]
Seems to be fixed by changes to CPU load detection ?

**Comment by canboat** [comment]
Correct, alas I mentioned the wrong issue in commit https://github.com/canboat/BR24radar_pi/commit/6da06e0edb5a504f01554e636f8bd5a87b07e001
