### ISSUE TITLE
Add separate radar-only display

### ISSUE THREAD

**Issue by canboat** [canboat/BR24radar_pi#34]
We ought to have a real separate radar display, without any charting underneath.

This allows side-by-side windows of pure radar and charting (possibly with radar overlay.) It also allows pure heads-up mode.

AIS on the radar only screen is nice to have, but not crucial. It should have nice range rings and heading information.

**Comment by NAHANNIV** [comment]
I think you are just talking about cloning the RADAR image in a different window, which I think would be good; But the 4G domes have second display functionality built in. If I understand correctly, using that functionality would allow different ranges and options in each window.

**Comment by canboat** [comment]
Work on this feature has started. See the 'radarwindow' branch.

What would be useful is what features you would like to see in this display.

I think we will start with "Head Up" mode (HU) with:
- Range rings
- North indication (if there is a compass)

Also, radar overlay can now revert back to only being shown if there is a GPS position and heading info.

**Comment by Hakansv** [comment]
No further features so far but two issues to discuss:

Alarm zones: Will these be visible on a black background screen? (Have to check)

AIS targets: On the present black "Radar only" HU screen charts are suppressed but AIS targets are clearly visible but on a false bearing. Not a problem if you know what's on the screen but can be confusing?
Håkan

**Comment by canboat** [comment]
Håkan, alarm zones will be displayed. AIS targets will not be displayed in V1. We'll have to rebuild AISradar_pi (but now for OpenGL, so we can't borrow that source code.)

**Comment by Hakansv** [comment]
OK....Thanks

**Comment by canboat** [comment]
Can finally close this now that v2.515 is out!
