### ISSUE TITLE
NMEA parser can crash on VDR data

### ISSUE THREAD

**Issue by canboat** [canboat/BR24radar_pi#69]
When using the VDR data recorder the plugin is reported to crash when compiled on Ubuntu.

VDR data:

    $AIHDT,045.0,T
    $GPGGA,174708.000,4311.8478,N,07934.4941,W,1,07,1.5,82.4,M,-34.7,M,,0000*56    
    $GPGSA,M,3,26,15,29,13,21,05,18,,,,,,3.6,1.5,3.3*39
    $GPRMC,174708.000,A,4311.8478,N,07934.4941,W,0.00,045.00,151214,,,A*7B

Crash dump:

    *** opencpn (wxWidgets 2.8.12) crashed ***, see backtrace!
    0x83577f6 in wxCrashPrint::Report() at ??:?
    0x8142324 in MyApp::OnFatalException() at ??:?
    0xb76679f3 in wxFatalSignalHandler at ??:0
    0xb76f7400 in [0xb76f7400] at ??:0
    0xb7629727 in wxStringBase::operator=(wxStringBase const&) at ??:0
    0x8162062 in wxString::operator=(wxString const&) at ??:?
    0x836e544 in NMEA0183::PreParse() at ??:?
    0xb2feb134 in NMEA0183::Parse() at ??:0
    0xb2fdcbbe in br24radar_pi::SetNMEASentence(wxString&) at ??:0
    0x82e5032 in PlugInManager::SendNMEASentenceToAllPlugIns(wxString const&) at ??:?
    0x8323868 in Multiplexer::OnEvtStream(OCPN_DataStreamEvent&) at ??:?
    0xb75d3df6 in wxAppConsole::HandleEvent(wxEvtHandler*, void (wxEvtHandler::*)(wxEvent&),     wxEvent&) const at ??:0
    0xb76646ae in wxEvtHandler::ProcessEventIfMatches(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) at ??:0
    0xb7664a49 in wxEvtHandler::SearchDynamicEventTable(wxEvent&) at ??:0
    0xb7664b0b in wxEvtHandler::ProcessEvent(wxEvent&) at ??:0
    0xb76645f8 in wxEvtHandler::ProcessPendingEvents() at ??:0
    0xb75d41a9 in wxAppConsole::ProcessPendingEvents() at ??:0
    0xb740b340 in wxAppBase::ProcessIdle() at ??:0
    0xb7376022 in  at ??:0
    0xb6579c50 in  at ??:0
    0xb657d0a7 in g_main_context_dispatch at ??:0
    0xb657d468 in  at ??:0
    0xb657d76b in g_main_loop_run at ??:0
    0xb68df450 in gtk_main at ??:0
    0xb738c17e in wxEventLoop::Run() at ??:0
    0xb740b14f in wxAppBase::MainLoop() at ??:0
    0xb740ac4f in wxAppBase::OnRun() at ??:0
    0xb7608d16 in wxEntry(int&, wchar_t**) at ??:0
    0xb7608db6 in wxEntry(int&, char**) at ??:0
    0x813d0c4 in main at ??:?
    Aborted

**Comment by douwefokkema** [comment]
I tried to reproduce this with OCPN 4.0 and wxWidgets 2.8.12 on Windows, no crash, runs fine. 
Same on Ubuntu OCPN4.1 with wxWidgets 3.0, running fine, also with radar (TCPreplay). Currently I do not have the Ubuntu with wxWidgets 2.8.12 installed so I cannot test that.
In these tests I used and a VDR file repeatedly containing the mentioned lines of NMEA output.

**Comment by douwefokkema** [comment]
I would like to have a look at the opencpn.conf file for this case. When testing under Ubuntu earlier most problems were related with the initializations.

**Comment by ptulp** [comment]
I have seen a similar problem with the logbook plugin (see CF Logbook Konni #664)
As far as I could determine the Parse function in the plugin did call the PreParse
in OpenPCN/src/ PreParse i.s.o. the PreParse in the plugin.
As I could not find the real reason for this I crudely solved it by renaming the NMEA0183 definitions
to NMEA0183L in the plugin. 
The problem was not seen after that. 
I am not very good at C++ so may be there is a better way to fix this as it can be seen for all plugins using NMEA I guess.

**Comment by NAHANNIV** [comment]
Here is my config file:

[PlugIns]
[PlugIns/GRIB]
bEnabled=1
[PlugIns/Dashboard]
bEnabled=1
Version=2
FontTitle=sans Italic 10
FontData=sans 14
FontLabel=sans 8
FontSmall=sans 8
DashboardCount=1
SpeedometerMax=12
SpeedUnit=0
DepthUnit=3
DistanceUnit=0
WindSpeedUnit=0
[PlugIns/Dashboard/Dashboard1]
Name=13722a40-8bee-486b-8d33-535a70b21439
Caption=Dashboard
Orientation=H
InstrumentCount=3
Instrument1=20
Instrument2=7
Instrument3=33
[PlugIns/Celestial]
bEnabled=1
[PlugIns/FindIt]
bEnabled=1
[PlugIns/VDR]
bEnabled=1
InputFilename=/home/nahanni/Desktop/Nema Stream.txt
OutputFilename=
Interval=1000
[PlugIns/Climatology]
bEnabled=1
[PlugIns/Logbook]
bEnabled=1
[PlugIns/WeatherFax]
bEnabled=1
[PlugIns/AIS\ Radar\ view]
bEnabled=1
[PlugIns/SAR]
bEnabled=1
[PlugIns/WMM]
bEnabled=1
[PlugIns/ROUTE]
bEnabled=1
[PlugIns/Calculator]
bEnabled=1
[PlugIns/rtlsdr]
bEnabled=1
[PlugIns/libSAR_i386_pi18_v08_pi.so]
bEnabled=0
[PlugIns/liblogbookkonni_i386_pi16_v11_pi.so]
bEnabled=0
[PlugIns/libclimatology_i386_pi19_v02_pi.so]
bEnabled=0
[PlugIns/libdashboard_pi.so]
bEnabled=1
[PlugIns/libroute_i386_pi18_v10_pi.so]
bEnabled=0
[PlugIns/libwmm_pi18_v07a_i386_pi.so]
bEnabled=0
[PlugIns/libaisradar_i386_pi17_v096_pi.so]
bEnabled=0
[PlugIns/libfindit_i386_pi16_v10_pi.so]
bEnabled=0
[PlugIns/libweatherfax_pi18_v06_i386_pi.so]
bEnabled=0
[PlugIns/libvdr_i386_pi16_v03_pi.so]
bEnabled=0
[PlugIns/libgrib_pi.so]
bEnabled=0
[PlugIns/librtlsdr_pi.so]
bEnabled=0
[PlugIns/libcalculator_i386_pi18_v13_pi.so]
bEnabled=0
[PlugIns/libcelestial_navigation_pi18_v15_1386_pi.so]
bEnabled=0
[PlugIns/libvdr_pi.so]
bEnabled=1
[PlugIns/BR24Radar]
DisplayOption=0
RangeUnits=1
DisplayMode=0
VerboseLog=0
Transparency=0
Gain=-1
RainGain=0
ClutterGain=-1
RangeCalibration=1
HeadingCorrection=0
BeamWidth=0
InterferenceRejection=0
TargetSeparation=0
NoiseRejection=0
TargetBoost=0
GuardZonesThreshold=0
GuardZonesRenderStyle=0
ScanMaxAge=4
DrawAlgorithm=0
ScanSpeed=0
Downsample=4
RadarAlertAudioFile=/usr/share/opencpn/sounds/collision555.wav
ControlsDialogSizeX=282
ControlsDialogSizeY=269
ControlsDialogPosX=624
ControlsDialogPosY=344
Zone1StBrng=0
Zone1EndBrng=0
Zone1OuterRng=0
Zone1InnerRng=0
Zone1ArcCirc=0
Zone2StBrng=0
Zone2EndBrng=0
Zone2OuterRng=0
Zone2InnerRng=0
Zone2ArcCirc=0
RunTimeOnIdle=2
Refreshrate=1
PassHeadingToOCPN=0
GuardZonePosX=20
GuardZonePosY=170
[PlugIns/libbr24radar_pi.so]
bEnabled=0
[ChartDirectories]
ChartDir1=/home/Charts/CA_CHTS^108852915322
ChartDir2=/home/Charts/Cm93 jan 2011^
[Settings]
ConfigVersionString=Version 4.0.0 Build 2015-01-08
NavMessageShown=1
UIStyle=Traditional
ChartNotRenderScaleFactor=2
ShowDebugWindows=1
SetSystemTime=0
ShowGrid=0
PlayShipsBells=0
FullscreenToolbar=1
TransparentToolbar=1
PermanentMOBIcon=0
ShowLayers=1
ShowDepthUnits=1
AutoAnchorDrop=0
ShowChartOutlines=1
ShowActiveRouteHighway=1
SDMMFormat=0
MostRecentGPSUploadConnection=
FilterNMEA_Avg=0
FilterNMEA_Sec=1
CM93DetailFactor=0
CM93DetailZoomPosX=200
CM93DetailZoomPosY=200
ShowCM93DetailSlider=0
AllowExtremeOverzoom=1
SkewToNorthUp=0
OpenGL=1
SmoothPanZoom=1
UseRasterCharts=1
UseVectorCharts=0
UseCM93Charts=0
CourseUpMode=0
LookAheadMode=0
COGUPAvgSeconds=15
OwnshipCOGPredictorMinutes=5
OwnShipIconType=0
OwnShipLength=0
OwnShipWidth=0
OwnShipGPSOffsetX=0
OwnShipGPSOffsetY=0
OwnShipMinSize=1
ChartQuilting=1
FullScreenQuilt=1
ChartQuiltingInitial=1
NMEALogWindowSizeX=600
NMEALogWindowSizeY=400
NMEALogWindowPosX=119
NMEALogWindowPosY=223
PreserveScaleOnX=1
StartWithTrackActive=0
AutomaticDailyTracks=0
HighlightTracks=1
InitialStackIndex=3
InitialdBIndex=69
ActiveChartGroup=0
AnchorWatch1GUID=
AnchorWatch2GUID=
ToolbarX=0
ToolbarY=0
ToolbarOrient=4
ToolbarConfig=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
GPSIdent=Generic
UseGarminHostUpload=0
PlanSpeed=4
VisibleLayers=
InvisibleLayers=
Locale=en
KeepNavobjBackups=5
ShowStatusBar=1
ShowMenuBar=0
ShowCompassWindow=1
DistanceFormat=0
SpeedFormat=0
ShowChartBar=1
ShowMag=0
UserMagVariation=0.00
ShowFPS=1
ZoomDetailFactor=0
FogOnOverzoom=0
OverzoomVectorScale=0
OverzoomEmphasisBase=10
UseAcceleratedPanning=1
GPUTextureCompression=1
GPUTextureCompressionCaching=1
GPUTextureDimension=512
GPUTextureMemSize=128
UseMagAPB=0
OwnshipCOGPredictorWidth=3
OwnshipHDTPredictorMiles=1
RouteArrivalCircleRadius=0.05
NMEAAPBPrecision=3
MobileTouch=0
ResponsiveGraphics=0
DisplaySizeMM=-1
LegacyInputCOMPortFilterBehaviour=0
Sailing=0
[Settings/ObjectFilter]
vizADMARE=1
vizAIRARE=1
vizACHBRT=1
vizACHPNT=1
vizACHARE=1
vizBCNCAR=1
vizBCNISD=1
vizBCNLAT=1
vizBCNSAW=1
vizBCNSPP=1
vizBERTHS=1
vizBRIDGE=1
vizBUISGL=1
vizBUIREL=1
vizBUAARE=1
vizBOYCAR=1
vizBOYINB=1
vizBOYISD=1
vizBOYLAT=1
vizBOYSAW=1
vizBOYSPP=1
vizCBLARE=1
vizCBLOHD=1
vizCBLSUB=1
vizCANALS=1
vizCANBNK=1
vizCTSARE=1
vizCAUSWY=1
vizCTNARE=1
vizCHNWIR=1
vizCHKPNT=1
vizCGUSTA=1
vizCOALNE=1
vizCONZNE=1
vizCOSARE=1
vizCTRPNT=1
vizCONVYR=1
vizCRANES=1
vizCURENT=1
vizCUSZNE=1
vizDAMCON=1
vizDAYMAR=1
vizDWRTCL=1
vizDWRTPT=1
vizDEPARE=1
vizDEPCNT=1
vizDISMAR=1
vizDOCARE=1
vizDRGARE=1
vizDRYDOC=1
vizDMPGRD=1
vizDYKCON=1
vizEXEZNE=1
vizFAIRWY=1
vizFNCLNE=1
vizFERYRT=1
vizFSHZNE=1
vizFSHFAC=1
vizFSHGRD=1
vizFLODOC=1
vizFOGSIG=1
vizFORSTC=1
vizFRPARE=1
vizGATCON=1
vizGRIDRN=1
vizHRBARE=1
vizHRBFAC=1
vizHULKES=1
vizICEARE=1
vizICNARE=1
vizISTZNE=1
vizLAKARE=1
vizLAKSHR=1
vizLNDARE=1
vizLNDELV=1
vizLNDRGN=1
vizLNDMRK=1
vizLIGHTS=1
viz_extgn=1
vizLITFLT=1
vizLITVES=1
vizLOCMAG=1
vizLOKBSN=1
vizLOGPON=1
vizMAGVAR=1
vizMARCUL=1
vizMIPARE=1
vizMONUMT=1
vizMORFAC=1
vizNAVLNE=1
vizOBSTRN=1
vizOFSPLF=1
vizOSPARE=1
vizOILBAR=1
vizPILPNT=1
vizPILBOP=1
vizPIPARE=1
vizPIPOHD=1
vizPIPSOL=1
vizPONTON=1
vizPRCARE=1
vizPRDARE=1
vizPYLONS=1
vizRADLNE=1
vizRADRNG=1
vizRADRFL=1
vizRADSTA=1
vizRTPBCN=1
vizRDOCAL=1
vizRDOSTA=1
vizRAILWY=1
vizRAPIDS=1
vizRCRTCL=1
vizRECTRC=1
vizRCTLPT=1
vizRSCSTA=1
vizRESARE=1
vizRETRFL=1
vizRIVERS=1
vizRIVBNK=1
vizROADWY=1
vizRUNWAY=1
vizSNDWAV=1
vizSEAARE=1
vizSPLARE=1
vizSBDARE=1
vizSLCONS=1
vizSISTAT=1
vizSISTAW=1
vizSILTNK=1
vizSLOTOP=1
vizSLOGRD=1
vizSMCFAC=1
vizSOUNDG=1
vizSPRING=1
vizSQUARE=1
vizSTSLNE=1
vizSUBTLN=1
vizSWPARE=1
vizTESARE=1
viz_texto=1
vizTS_PRH=1
vizTS_PNH=1
vizTS_PAD=1
vizTS_TIS=1
vizT_HMON=1
vizT_NHMN=1
vizT_TIMS=1
vizTIDEWY=1
vizTOPMAR=1
vizTOWERS=1
vizTSELNE=1
vizTSSBND=1
vizTSSCRS=1
vizTSSLPT=1
vizTSSRON=1
vizTSEZNE=1
vizTUNNEL=1
vizTWRTPT=1
vizUWTROC=1
vizUNSARE=1
vizVEGATN=1
vizWATTUR=1
vizWATFAL=1
vizWEDKLP=1
vizWRECKS=1
vizZEMCNT=1
vizTS_FEB=1
vizM_ACCY=1
vizM_CSCL=1
vizM_COVR=1
vizM_HDAT=1
vizM_HOPA=1
vizM_NPUB=1
vizM_NSYS=1
vizM_PROD=1
vizM_QUAL=1
vizM_SDAT=1
vizM_SREL=1
vizM_UNIT=1
vizM_VDAT=1
vizC_AGGR=1
vizC_ASSO=1
vizC_STAC=1
viz\$AREAS=1
viz\$LINES=1
viz\$CSYMB=1
viz\$COMPS=1
viz\$TEXTS=1
viznotmrk=1
vizwtwaxs=1
vizwtwprf=1
vizbrgare=1
vizbunsta=1
vizcomare=1
vizhrbbsn=1
vizlokare=1
vizlkbspt=1
vizprtare=1
vizbcnwtw=1
vizboywtw=1
vizrefdmp=1
vizrtplpt=1
viztermnl=1
viztrnbsn=1
vizwtware=1
vizwtwgag=1
viztisdge=1
vizvehtrf=1
vizexcnst=1
vizlg_sdm=1
vizlg_vsp=1
viz_cmapl=1
vizANNOTA=0
vizRESTRC=0
vizTRFLNE=0
vizGENNAV=0
[Settings/GlobalState]
VPLatLon="   43.1975,  -79.5749"
VPScale=0.552779
OwnShipLatLon="   43.1975,   -79.5749"
bFollow=1
nColorScheme=0
FrameWinX=1400
FrameWinY=993
FrameWinPosX=0
FrameWinPosY=0
FrameMax=1
ClientPosX=0
ClientPosY=0
ClientSzX=1400
ClientSzY=1016
bShowS57Text=1
bShowS57ImportantTextOnly=0
nDisplayCategory=79
nSymbolStyle=82
nBoundaryStyle=78
bShowSoundg=1
bShowMeta=1
bUseSCAMIN=1
bShowAtonText=1
bShowLightDescription=1
bExtendLightSectors=0
bDeClutterText=1
S52_MAR_SAFETY_CONTOUR=8.001
S52_MAR_SHALLOW_CONTOUR=2.99923
S52_MAR_DEEP_CONTOUR=10.0005
S52_MAR_TWO_SHADES=0
S52_DEPTH_UNIT_SHOW=0
VPRotation=0
bShowNationalText=0
[Settings/AIS]
bNoCPAMax=1
NoCPAMaxNMi=20
bCPAWarn=1
CPAWarnNMi=2
bTCPAMax=1
TCPAMaxMinutes=30
bMarkLostTargets=1
MarkLost_Minutes=8
bRemoveLostTargets=1
RemoveLost_Minutes=10
bShowCOGArrows=1
CogArrowMinutes=6
bShowTargetTracks=1
TargetTracksMinutes=20
bShowMooredTargets=1
MooredTargetMaxSpeedKnots=0.2
bAISAlertDialog=1
bAISAlertAudio=1
AISAlertAudioFile=/usr/share/opencpn/sounds/1bells.wav
bAISAlertSuppressMoored=1
bShowAreaNotices=1
bDrawAISSize=1
AlertDialogSizeX=310
AlertDialogSizeY=462
AlertDialogPosX=42
AlertDialogPosY=149
QueryDialogPosX=525
QueryDialogPosY=164
AISTargetListPerspective=name=AISTargetList;caption=AIS target list;state=2103265;dir=4;layer=0;row=0;pos=0;prop=100000;bestw=780;besth=249;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=511;floaty=92;floatw=824;floath=419
AISTargetListRange=40
AISTargetListSortColumn=2
bAISTargetListSortReverse=0
AISTargetListColumnSpec=182;55;80;55;80;90;45;62;50;50;54;
S57QueryDialogSizeX=400
S57QueryDialogSizeY=400
bAISRolloverShowClass=1
bAISRolloverShowCOG=1
bAISRolloverShowCPA=1
bAISAlertAckTimeout=0
AlertAckTimeoutMinutes=0
bShowAISName=0
ShowAISTargetNameScale=250000
bWplIsAprsPositionReport=1
AISCOGPredictorWidth=3
[Settings/NMEADataSource]
DataConnections=
[Settings/Others]
ShowRadarRings=0
RadarRingsNumberVisible=0
RadarRingsStep=1
RadarRingsStepUnits=0
ConfirmObjectDeletion=1
WaypointPreventDragging=0
EnableZoomToCursor=1
TrackIntervalSeconds=60
TrackDeltaDistance=0.1
TrackPrecision=0
RouteLineWidth=2
TrackLineWidth=3
CurrentArrowScale=100
DefaultWPIcon=triangle
[Settings/Route_pi]
Opacity=255
DialogPosX=20
DialogPosY=20
[Settings/WMM]
ViewType=1
ShowAtCursor=1
ShowLiveIcon=1
Opacity=255
DialogPosX=20
DialogPosY=20
[Settings/WMM/Plot]
Declination=1
DeclinationSpacing=10
Inclination=0
InclinationSpacing=10
FieldStrength=0
FieldStrengthSpacing=10000
StepSize=6
PoleAccuracy=2
[Settings/rtlsdr]
DialogPosX=1208
DialogPosY=296
Enabled=1
Mode=0
AISProgram=0
AISSampleRate=256
AISError=57
ADSBPlot=1
FMFrequency=104.4
VHFChannel=16
VHFWX=0
[Settings/WeatherFax]
Path=
DialogPosX=20
DialogPosY=20
[Settings/WeatherFax/Audio]
ImageWidth=1152
BitsPerPixel=8
Carrier=1900
Deviation=400
Filter=1
SkipHeaderDetection=0
IncludeHeadersInImage=0
[Settings/Calculator]
Opacity=255
MaxResults=255
DialogPosX=20
DialogPosY=20
DialogPosW=20
DialogPosH=20
m_bshowhelpB=1
m_bshowhistoryB=1
m_bCalculateB=1
m_bshowhistory=1
m_bcapturehidden=1
m_blogresults=1
[Settings/SAR_pi]
Opacity=255
DialogPosX=20
DialogPosY=20
CaptureCursor=1
CaptureShip=1
[Settings/GTKFonts]
-1d03864b=AISTargetAlert:Ubuntu 12:rgb(0, 0, 0)
-1e238651=AISTargetQuery:Ubuntu 12:rgb(0, 0, 0)
-6711839b=RouteLegInfoRollover:Ubuntu 12:rgb(0, 0, 0)
-89851d0f=ObjectQuery:Ubuntu 12:rgb(0, 0, 0)
-a1a382bd=AISRollover:Ubuntu 12:rgb(0, 0, 0)
en-09b97775=Menu:Ubuntu 11:rgb(0, 0, 0)
en-1d03864b=AISTargetAlert:Ubuntu 11:rgb(0, 0, 0)
en-1e238651=AISTargetQuery:Ubuntu 11:rgb(0, 0, 0)
en-3582063a=ChartTexts:Ubuntu 11:rgb(0, 0, 0)
en-49dc24be=AIS Target Name:Ubuntu 11:rgb(0, 0, 0)
en-6052cba4=Console Value:Ubuntu 11:rgb(0, 0, 0)
en-6711839b=RouteLegInfoRollover:Ubuntu 11:rgb(0, 0, 0)
en-68c1d6c4=Console Legend:Ubuntu 11:rgb(0, 0, 0)
en-89851d0f=ObjectQuery:Ubuntu 11:rgb(0, 0, 0)
en-9c3b3a0d=Dialog:Ubuntu 11:rgb(0, 0, 0)
en-a1a382bd=AISRollover:Ubuntu 11:rgb(0, 0, 0)
en-b25a3899=StatusBar:Ubuntu 11:rgb(0, 0, 0)
en-cb4437f1=ToolTips:Ubuntu 11:rgb(0, 0, 0)
en-dc3cb5f7=Marks:Ubuntu 12:rgb(0, 0, 0)
en-df0f7403=CurrentValue:Ubuntu 11:rgb(0, 0, 0)
en-e441042a=ExtendedTideIcon:Ubuntu 11:rgb(0, 0, 0)
en-fbbaefb3=TideCurrentGraphRollover:Ubuntu 11:rgb(0, 0, 0)
en_US-3582063a=ChartTexts:Ubuntu 12:rgb(0, 0, 0)
en_US-6052cba4=Console Value:Ubuntu 12:rgb(0, 0, 0)
en_US-68c1d6c4=Console Legend:Ubuntu 12:rgb(0, 0, 0)
en_US-b25a3899=StatusBar:Ubuntu 12:rgb(0, 0, 0)
en_US-cb4437f1=ToolTips:Ubuntu 12:rgb(0, 0, 0)
[Directories]
S57DataLocation=
SENCFileLocation=
InitChartDir=/home/Charts
GPXIODir=
TCDataDir=/usr/share/opencpn/tcdata/europe
WMMDataLocation=//plugins
WeatherFaxDataLocation=//plugins
[AUI]
AUIPerspective=layout2|name=ChartCanvas;caption=;state=768;dir=5;layer=0;row=0;pos=0;prop=100000;bestw=1400;besth=968;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=13722a40-8bee-486b-8d33-535a70b21439;caption=Dashboard;state=2099187;dir=4;layer=0;row=0;pos=0;prop=100000;bestw=450;besth=167;minw=450;minh=167;maxw=-1;maxh=-1;floatx=3;floaty=601;floatw=726;floath=365|dock_size(5,0,0)=285|
[Groups]
GroupCount=0
[TideCurrentDataSources]
tcds0=/usr/share/opencpn/tcdata/HARMONIC.IDX
tcds1=/usr/share/opencpn/tcdata/europe/HARMONIC.IDX

**Comment by NAHANNIV** [comment]
Here is my logfile up to the crash:

08:28:55 EDT: 2015-05-22
08:28:55 EDT:  ------- Starting OpenCPN -------
08:28:55 EDT: Version 4.0.0 Build 2015-01-08
08:28:55 EDT: wxWidgets version: wxWidgets 2.8.12
08:28:55 EDT: MemoryStatus:  mem_total: 495 mb,  mem_initial: 9 mb
08:28:55 EDT: SData_Locn is /usr/share/opencpn/
08:28:55 EDT: Using existing Config_File: /home/nahanni/.opencpn/opencpn.conf
08:28:55 EDT: Styles loading from /usr/share/opencpn/uidata/styles.xml
08:28:55 EDT: No styles found at: /home/nahanni/
08:28:55 EDT: No styles found at: /home/nahanni/.opencpn/
08:28:55 EDT: Detected display size: 370 mm
08:28:55 EDT: Detected display size: 370 mm
08:28:55 EDT: Setting Viewpoint Lat/Lon 43.1975, -79.5749
08:28:55 EDT: Setting Ownship Lat/Lon 43.1975, -79.5749
08:28:55 EDT: Loading navobjects from navobj.xml
08:28:55 EDT: Done loading navobjects
08:28:55 EDT: System default Language:  en_US
08:28:55 EDT: Opencpn language set to:  en_GB
08:28:56 EDT: ChartSymbols loaded from /usr/share/opencpn/s57data/chartsymbols.xml
08:28:56 EDT: Using s57data in /usr/share/opencpn/s57data
08:28:56 EDT: Setting Viewpoint Lat/Lon 43.1975, -79.5749
08:28:56 EDT: Setting Ownship Lat/Lon 43.1975, -79.5749
08:28:56 EDT: Creating glChartCanvas
08:28:56 EDT: PlugInManager searching for PlugIns in location /usr/lib/opencpn
08:28:56 EDT: PlugInManager: Loading PlugIn: /usr/lib/opencpn/libvdr_pi.so
08:28:56 EDT:   /usr/lib/opencpn/libvdr_pi.so
              API Version detected: 106
              PlugIn Version detected: 3
08:28:56 EDT: Opencpn language reload for:  en_GB
08:28:56 EDT: Loading catalog for:  opencpn-vdr_pi
08:28:56 EDT: Loading catalog for opencpn core.
08:28:56 EDT: PlugInManager: Loading PlugIn: /usr/lib/opencpn/libdashboard_pi.so
08:28:56 EDT:   /usr/lib/opencpn/libdashboard_pi.so
              API Version detected: 106
              PlugIn Version detected: 102
08:28:56 EDT: Opencpn language reload for:  en_GB
08:28:56 EDT: Loading catalog for:  opencpn-vdr_pi
08:28:56 EDT: Loading catalog for:  opencpn-dashboard_pi
08:28:56 EDT: Loading catalog for opencpn core.
08:28:56 EDT: PlugInManager: Loading PlugIn: /usr/lib/opencpn/libbr24radar_pi.so
08:28:56 EDT:   /usr/lib/opencpn/libbr24radar_pi.so
              API Version detected: 110
              PlugIn Version detected: 102
08:28:56 EDT: Opencpn language reload for:  en_GB
08:28:56 EDT: Loading catalog for:  opencpn-vdr_pi
08:28:56 EDT: Loading catalog for:  opencpn-dashboard_pi
08:28:56 EDT: Loading catalog for:  opencpn-br24radar_pi
08:28:56 EDT: Loading catalog for opencpn core.
08:28:56 EDT: BR24radar_pi: Configuration file values initialised
08:28:56 EDT: BR24radar_pi: Log verbosity = 0 (to modify, set VerboseLog to 0..4)
08:28:56 EDT: BR24radar_pi: GuardZone 1: Off
08:28:56 EDT: BR24radar_pi: GuardZone 2: Off
08:28:56 EDT: OpenGL-> Renderer String: Gallium 0.4 on ATI RV350
08:28:56 EDT: OpenGL-> Version reported:  2.1 Mesa 10.1.3
08:28:56 EDT: OpenGL-> Texture rectangle format: de1
08:28:56 EDT: OpenGL-> glGenerateMipmap unavailable
08:28:56 EDT: OpenGL-> Using Vertexbuffer Objects
08:28:56 EDT: OpenGL-> Using Framebuffer Objects
08:28:56 EDT: OpenGL-> Using FBO Stencil buffer
08:28:56 EDT: OpenGL-> Using Stencil buffer clipping
08:28:56 EDT: OpenGL-> Using Scissor Clipping
08:28:56 EDT: OpenGL-> Using s3tc dxt1 compression
08:28:56 EDT: OpenGL-> Compressed tile size: 128kb (6:1)
08:28:56 EDT: OpenGL-> Minimum cartographic line width:  1.0
08:28:56 EDT: OpenGL-> Minimum symbol line width:  1.0
08:28:57 EDT: ChartDB Cache policy:  Application target is 242 MBytes
08:28:57 EDT: Loading chart db version: V018
08:28:57 EDT: Chartdb: Chart directory list follows
08:28:57 EDT:   Chart directory #0: /home/Charts/CA_CHTS
08:28:57 EDT:   Chart directory #1: /home/Charts/Cm93 jan 2011
08:28:57 EDT: GPS Watchdog Timeout is: 6 sec.
08:28:57 EDT: Initializing Chart /home/Charts/Cm93 jan 2011
08:28:57 EDT: CM93Composite Chart Root is /home/Charts/Cm93 jan 2011/
08:28:57 EDT: Loaded CM93 Dictionary from /home/Charts/Cm93 jan 2011/
08:28:58 EDT: Loading CM93 cell /home/Charts/Cm93 jan 2011/03900840/E/03990841.E
08:28:58 EDT: Loading CM93 cell /home/Charts/Cm93 jan 2011/03900840/D/03990840.D
08:29:00 EDT:    ***GPS Watchdog timeout at Lat:43.1975   Lon: -79.5749
08:29:12 EDT: Changing NMEA Datasource for GPGGA to  (Priority: 0)
08:29:13 EDT: BR24radar_pi: GPS position is now known
08:29:13 EDT: Changing NMEA Datasource for GPGSA to  (Priority: 0)
08:29:14 EDT: Changing NMEA Datasource for GPRMC to  (Priority: 0)
08:29:15 EDT: BR24radar_pi: Heading source is now COG
08:29:16 EDT: Changing NMEA Datasource for AIHDT to  (Priority: 0)
08:29:17 EDT: BR24radar_pi: Heading source is now HDT
08:29:27 EDT:

**Comment by NAHANNIV** [comment]
Perhaps I should just update to latest OpenCPN and wxWidgits 3.0 ?

**Comment by douwefokkema** [comment]
I tested with your .conf  / .ini file under Win7 (OCPN4.0), no problems.
On Ubuntu (OCPN4.1 wxWidgets 3.0) it seems to run fine, but I get following error messages when opening the options window after having run the radar_pi with your VDR file:

(opencpn:2430): Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width -5 and height 17

and on a next run:

(opencpn:2715): Gdk-CRITICAL **: IA__gdk_draw_layout: assertion 'PANGO_IS_LAYOUT (layout)' failed
(opencpn:2715): Pango-CRITICAL **: pango_layout_get_line_count: assertion 'layout != NULL' failed

So there must be something wrong in the radar_pi. Needs more time to investigate.

**Comment by NAHANNIV** [comment]
I get the GTK warnings all the time on this UBUNTU laptop and my ARM platform.
I was told by NOHAL that it's normal.

I also have no problem with the current version on Win7.

A previous version of the plugin worked on my UBUNTU laptop; I was able to use it on my boat and see an excellent RADAR image. Then I built latest br24 from source, and have not been able to get it to work.

I think later I will try to update everything to latest versions.

**Comment by canboat** [comment]
@NAHANNIV it is probably more helpful if you rebuild both O and the plugin using the debug build. Once you've done this then please upload the backtrace. If compiled with debug this will include line numbers and source files.

This could very well be related to wx 2.8.12 which is why it doesn't show up on newer releases.

**Comment by canboat** [comment]
@NAHANNIV, commit c68abc3 implements @ptulp 's suggestion. Can you try again? Note that this is NOT in the Beta released earlier today.

**Comment by NAHANNIV** [comment]
I was at the boat this weekend, eager to try the RADAR, so I updated to the latest of everything before I got the message from canboat about a special version: OpenCPN 4.1.427, wxWidgets 3.0, br25_pi.

I still had wxWidgets (3.0) crashing.

Then I noticed that OpenCPN 4.0 had not been uninstalled (I had used: $ sudo apt-get remove opencpn) before building the latest.

I was eventually able to get it to work by disabling the br24 plugin in both versions of OpenCPN then re-enabling it in the latest.

This was all on NAVIGATRIX(Ubuntu) which came with OpenCPN 3.? and was upgraded with the 4.0 package, then most recently to 4.1.427 from source.

It's working now, I'm not sure if anything can be gained from examining what happened ?

**Comment by canboat** [comment]
Ah yes that explains it I have been caught out by multiple installs as well. Let me check if I can add a detection mechanism.

**Comment by canboat** [comment]
I will close this then and open a long term issue for detecting multiple instances of the plugin.

**Comment by NAHANNIV** [comment]
Ok with me.
