### ISSUE TITLE
Shader causes hangs and core dumps on Microsoft Windows

### ISSUE THREAD

**Issue by canboat** [canboat/BR24radar_pi#89]
Sean's shader code works great on Linux and OS X, but on Microsoft Windows it is not working right according to various testers.

**Comment by douwefokkema** [comment]
Earlier I reported that crashes seemed to be over. I tested again in the earlier tested version and in the most recent (73e39c5). Both still have the crash after a varying amount of time (1 - 20 seconds) when using shader.

**Comment by canboat** [comment]
Shader works well in v2.515.
