### ISSUE TITLE
Alarm zone dialog don't appear

### ISSUE THREAD

**Issue by franciscocr** [canboat/BR24radar_pi#98]
Hello i am testing your very nice plugin but we have one problem the alarm zone dialog don't appear i don't know what is the problem i use opencpn 4.1.1317 and the br24radar_pi v1.3. with windows 8.1

Thanks so much

![zone](https://cloud.githubusercontent.com/assets/14102765/12697290/a0d98a02-c75e-11e5-8f50-ac30873968d9.png)

**Comment by canboat** [comment]
There are no echos in the green guard zone, so the dialog doesn't show. It will pop up if a certain treshold of echos is inside the guard zone.
